#!/bin/bash -l
# This is a job submission file on the njit cluster Lochness.
# This is necessary for long computations of large mesh files.
# Submit this by typing `sbatch lochjob`

## NAMING
#SBATCH -J testjobname
#SBATCH -p public
#SBATCH -o test.output
#SBATCH -e test.output

## EMAIL NOTIFICATION
#SBATCH --mail-user tt73@njit.edu
#SBATCH --mail-type=ALL
#SBATCH -A tt73

## RUNTIME  HOURS:MIN:SEC and MEMORY 
#SBATCH -t 5:0:0
#SBATCH --mem=64G

module load python 
module load gnu8
module load mpich 
module load petsc/3.12.0

python3 example2.py >> outfile