#!/bin/bash -l
## This is a test to run the NASM on one subdomain. It's equivalent to Newton's method.
## DGMRES with SSOR PC is used for the linear system.
## The number of subdomain iterations has been increased from 50 to 10000 for the serial case.

## Set the name of job
#SBATCH -J serial1
#SBATCH -p public

## Set partition/queue
#SBATCH -p dms-cpu

## Set email notification
#SBATCH --mail-user tt73@njit.edu
#SBATCH --mail-type=END
#SBATCH -A tt73

## RUNTIME  HOURS:MIN:SEC and MEMORY
#SBATCH -t 8:0:0
#SBATCH --mem=16G
#SBATCH -N 1

## Modules needed for PETSc
module load gnu8 mpich petsc

rm -f out1

for N in 100 150 200 250 300 350 400 450 500
do
   printf "N = $N:\n" >> out1
   ../../maddm -N $N -problem ex1 >> out1
   ../../maddm -N $N -problem ex2 >> out1
   ../../maddm -N $N -problem ex3 >> out1
   ../../maddm -N $N -problem ex4 >> out1
done
