#!/bin/bash -l
# This is a job submission file on the njit cluster Stheno.
# Submit this by typing `sbatch shjob`

## Set the name of job
#SBATCH -J serial1
#SBATCH -p public

## Set partition/queue
#SBATCH -p dms-cpu

## Set email notification
#SBATCH --mail-user tt73@njit.edu
#SBATCH --mail-type=ALL
#SBATCH -A tt73

## RUNTIME  HOURS:MIN:SEC and MEMORY
#SBATCH -t 8:0:0
#SBATCH --mem=16G
#SBATCH -N 1

## Modules needed for PETSc
module load gnu8 mpich petsc

bash test1.sh > out_test1b