#!/bin/bash -l
## This

## Set the name of job
#SBATCH -J serial2
#SBATCH -p public

## Set partition/queue
#SBATCH -p dms-cpu

## Set email notification
#SBATCH --mail-user tt73@njit.edu
#SBATCH --mail-type=END
#SBATCH -A tt73

## RUNTIME  HOURS:MIN:SEC and MEMORY
#SBATCH -t 8:0:0
#SBATCH --mem=16G
#SBATCH -N 1

## Modules needed for PETSc
module load gnu8 mpich petsc

for N in 100 150 200 250 300 350 400 450 500
do
   printf "N = $N:\n" >> out2
   ../../maddm -N $N -problem ex1 -snes_type newtonls >> out2
   ../../maddm -N $N -problem ex2 -snes_type newtonls >> out2
   ../../maddm -N $N -problem ex3 -snes_type newtonls >> out2
done
