Starting /home/t/tt73/.bash_profile ... standard AFS bash profile

========================
Home directory : /home/t/tt73 is not in AFS -- skipping quota check
========================

On host node012 :
	 14:36:24 up 577 days, 23:37,  0 users,  load average: 0.12, 0.07, 0.06

=== === === Your Kerberos ticket and AFS token status === === ===
klist: No credentials cache found (filename: /tmp/krb5cc_90502_uK4JewCEBu)
Kerberos : 
AFS      : 

Loading default modules ...
Create file : "/home/t/tt73/.modules" to customize.


Currently Loaded Modules:
  1) python/3.8   3) mpich/3.3.1    5) openblas/0.3.7    7) petsc/3.12.0
  2) gnu8/8.3.0   4) phdf5/1.10.5   6) scalapack/2.0.2

 

[-0.5, 0.5]^2
tol = 1e-1
N = 20
Now running mpiexec -np 1 ../../maddm -N 20 -problem ex1 -sub_snes_rtol 1e-1 -sub_ksp_rtol 1e-1 -xmin -0.5 -xmax 0.5 -ymin -0.5 -ymax 0.5
N = 100
Now running mpiexec -np 1 ../../maddm -N 100 -problem ex1 -sub_snes_rtol 1e-1 -sub_ksp_rtol 1e-1 -xmin -0.5 -xmax 0.5 -ymin -0.5 -ymax 0.5
N = 200
Now running mpiexec -np 1 ../../maddm -N 200 -problem ex1 -sub_snes_rtol 1e-1 -sub_ksp_rtol 1e-1 -xmin -0.5 -xmax 0.5 -ymin -0.5 -ymax 0.5
tol = 1e-2
N = 20
Now running mpiexec -np 1 ../../maddm -N 20 -problem ex1 -sub_snes_rtol 1e-2 -sub_ksp_rtol 1e-2 -xmin -0.5 -xmax 0.5 -ymin -0.5 -ymax 0.5
N = 100
Now running mpiexec -np 1 ../../maddm -N 100 -problem ex1 -sub_snes_rtol 1e-2 -sub_ksp_rtol 1e-2 -xmin -0.5 -xmax 0.5 -ymin -0.5 -ymax 0.5
N = 200
Now running mpiexec -np 1 ../../maddm -N 200 -problem ex1 -sub_snes_rtol 1e-2 -sub_ksp_rtol 1e-2 -xmin -0.5 -xmax 0.5 -ymin -0.5 -ymax 0.5
tol = 1e-3
N = 20
Now running mpiexec -np 1 ../../maddm -N 20 -problem ex1 -sub_snes_rtol 1e-3 -sub_ksp_rtol 1e-3 -xmin -0.5 -xmax 0.5 -ymin -0.5 -ymax 0.5
N = 100
Now running mpiexec -np 1 ../../maddm -N 100 -problem ex1 -sub_snes_rtol 1e-3 -sub_ksp_rtol 1e-3 -xmin -0.5 -xmax 0.5 -ymin -0.5 -ymax 0.5
N = 200
Now running mpiexec -np 1 ../../maddm -N 200 -problem ex1 -sub_snes_rtol 1e-3 -sub_ksp_rtol 1e-3 -xmin -0.5 -xmax 0.5 -ymin -0.5 -ymax 0.5
tol = 1e-4
N = 20
Now running mpiexec -np 1 ../../maddm -N 20 -problem ex1 -sub_snes_rtol 1e-4 -sub_ksp_rtol 1e-4 -xmin -0.5 -xmax 0.5 -ymin -0.5 -ymax 0.5
N = 100
Now running mpiexec -np 1 ../../maddm -N 100 -problem ex1 -sub_snes_rtol 1e-4 -sub_ksp_rtol 1e-4 -xmin -0.5 -xmax 0.5 -ymin -0.5 -ymax 0.5
N = 200
Now running mpiexec -np 1 ../../maddm -N 200 -problem ex1 -sub_snes_rtol 1e-4 -sub_ksp_rtol 1e-4 -xmin -0.5 -xmax 0.5 -ymin -0.5 -ymax 0.5
tol = 1e-5
N = 20
Now running mpiexec -np 1 ../../maddm -N 20 -problem ex1 -sub_snes_rtol 1e-5 -sub_ksp_rtol 1e-5 -xmin -0.5 -xmax 0.5 -ymin -0.5 -ymax 0.5
N = 100
Now running mpiexec -np 1 ../../maddm -N 100 -problem ex1 -sub_snes_rtol 1e-5 -sub_ksp_rtol 1e-5 -xmin -0.5 -xmax 0.5 -ymin -0.5 -ymax 0.5
N = 200
Now running mpiexec -np 1 ../../maddm -N 200 -problem ex1 -sub_snes_rtol 1e-5 -sub_ksp_rtol 1e-5 -xmin -0.5 -xmax 0.5 -ymin -0.5 -ymax 0.5
tol = 1e-6
N = 20
Now running mpiexec -np 1 ../../maddm -N 20 -problem ex1 -sub_snes_rtol 1e-6 -sub_ksp_rtol 1e-6 -xmin -0.5 -xmax 0.5 -ymin -0.5 -ymax 0.5
N = 100
Now running mpiexec -np 1 ../../maddm -N 100 -problem ex1 -sub_snes_rtol 1e-6 -sub_ksp_rtol 1e-6 -xmin -0.5 -xmax 0.5 -ymin -0.5 -ymax 0.5
N = 200
Now running mpiexec -np 1 ../../maddm -N 200 -problem ex1 -sub_snes_rtol 1e-6 -sub_ksp_rtol 1e-6 -xmin -0.5 -xmax 0.5 -ymin -0.5 -ymax 0.5
[-1.0, 1.0]^2
tol = 1e-1
N = 40
Now running mpiexec -np 1 ../../maddm -N 40 -problem ex1 -sub_snes_rtol 1e-1 -sub_ksp_rtol 1e-1 -xmin -1.0 -xmax 1.0 -ymin -1.0 -ymax 1.0
N = 200
Now running mpiexec -np 1 ../../maddm -N 200 -problem ex1 -sub_snes_rtol 1e-1 -sub_ksp_rtol 1e-1 -xmin -1.0 -xmax 1.0 -ymin -1.0 -ymax 1.0
N = 400
Now running mpiexec -np 1 ../../maddm -N 400 -problem ex1 -sub_snes_rtol 1e-1 -sub_ksp_rtol 1e-1 -xmin -1.0 -xmax 1.0 -ymin -1.0 -ymax 1.0
tol = 1e-2
N = 40
Now running mpiexec -np 1 ../../maddm -N 40 -problem ex1 -sub_snes_rtol 1e-2 -sub_ksp_rtol 1e-2 -xmin -1.0 -xmax 1.0 -ymin -1.0 -ymax 1.0
N = 200
Now running mpiexec -np 1 ../../maddm -N 200 -problem ex1 -sub_snes_rtol 1e-2 -sub_ksp_rtol 1e-2 -xmin -1.0 -xmax 1.0 -ymin -1.0 -ymax 1.0
N = 400
Now running mpiexec -np 1 ../../maddm -N 400 -problem ex1 -sub_snes_rtol 1e-2 -sub_ksp_rtol 1e-2 -xmin -1.0 -xmax 1.0 -ymin -1.0 -ymax 1.0
tol = 1e-3
N = 40
Now running mpiexec -np 1 ../../maddm -N 40 -problem ex1 -sub_snes_rtol 1e-3 -sub_ksp_rtol 1e-3 -xmin -1.0 -xmax 1.0 -ymin -1.0 -ymax 1.0
N = 200
Now running mpiexec -np 1 ../../maddm -N 200 -problem ex1 -sub_snes_rtol 1e-3 -sub_ksp_rtol 1e-3 -xmin -1.0 -xmax 1.0 -ymin -1.0 -ymax 1.0
N = 400
Now running mpiexec -np 1 ../../maddm -N 400 -problem ex1 -sub_snes_rtol 1e-3 -sub_ksp_rtol 1e-3 -xmin -1.0 -xmax 1.0 -ymin -1.0 -ymax 1.0
tol = 1e-4
N = 40
Now running mpiexec -np 1 ../../maddm -N 40 -problem ex1 -sub_snes_rtol 1e-4 -sub_ksp_rtol 1e-4 -xmin -1.0 -xmax 1.0 -ymin -1.0 -ymax 1.0
N = 200
Now running mpiexec -np 1 ../../maddm -N 200 -problem ex1 -sub_snes_rtol 1e-4 -sub_ksp_rtol 1e-4 -xmin -1.0 -xmax 1.0 -ymin -1.0 -ymax 1.0
N = 400
Now running mpiexec -np 1 ../../maddm -N 400 -problem ex1 -sub_snes_rtol 1e-4 -sub_ksp_rtol 1e-4 -xmin -1.0 -xmax 1.0 -ymin -1.0 -ymax 1.0
tol = 1e-5
N = 40
Now running mpiexec -np 1 ../../maddm -N 40 -problem ex1 -sub_snes_rtol 1e-5 -sub_ksp_rtol 1e-5 -xmin -1.0 -xmax 1.0 -ymin -1.0 -ymax 1.0
N = 200
Now running mpiexec -np 1 ../../maddm -N 200 -problem ex1 -sub_snes_rtol 1e-5 -sub_ksp_rtol 1e-5 -xmin -1.0 -xmax 1.0 -ymin -1.0 -ymax 1.0
N = 400
Now running mpiexec -np 1 ../../maddm -N 400 -problem ex1 -sub_snes_rtol 1e-5 -sub_ksp_rtol 1e-5 -xmin -1.0 -xmax 1.0 -ymin -1.0 -ymax 1.0
tol = 1e-6
N = 40
Now running mpiexec -np 1 ../../maddm -N 40 -problem ex1 -sub_snes_rtol 1e-6 -sub_ksp_rtol 1e-6 -xmin -1.0 -xmax 1.0 -ymin -1.0 -ymax 1.0
N = 200
Now running mpiexec -np 1 ../../maddm -N 200 -problem ex1 -sub_snes_rtol 1e-6 -sub_ksp_rtol 1e-6 -xmin -1.0 -xmax 1.0 -ymin -1.0 -ymax 1.0
N = 400
Now running mpiexec -np 1 ../../maddm -N 400 -problem ex1 -sub_snes_rtol 1e-6 -sub_ksp_rtol 1e-6 -xmin -1.0 -xmax 1.0 -ymin -1.0 -ymax 1.0
[-1.5, 1.5]^2
tol = 1e-1
N = 60
Now running mpiexec -np 1 ../../maddm -N 60 -problem ex1 -sub_snes_rtol 1e-1 -sub_ksp_rtol 1e-1 -xmin -1.5 -xmax 1.5 -ymin -1.5 -ymax 1.5
N = 300
Now running mpiexec -np 1 ../../maddm -N 300 -problem ex1 -sub_snes_rtol 1e-1 -sub_ksp_rtol 1e-1 -xmin -1.5 -xmax 1.5 -ymin -1.5 -ymax 1.5
N = 600
Now running mpiexec -np 1 ../../maddm -N 600 -problem ex1 -sub_snes_rtol 1e-1 -sub_ksp_rtol 1e-1 -xmin -1.5 -xmax 1.5 -ymin -1.5 -ymax 1.5
tol = 1e-2
N = 60
Now running mpiexec -np 1 ../../maddm -N 60 -problem ex1 -sub_snes_rtol 1e-2 -sub_ksp_rtol 1e-2 -xmin -1.5 -xmax 1.5 -ymin -1.5 -ymax 1.5
N = 300
Now running mpiexec -np 1 ../../maddm -N 300 -problem ex1 -sub_snes_rtol 1e-2 -sub_ksp_rtol 1e-2 -xmin -1.5 -xmax 1.5 -ymin -1.5 -ymax 1.5
N = 600
Now running mpiexec -np 1 ../../maddm -N 600 -problem ex1 -sub_snes_rtol 1e-2 -sub_ksp_rtol 1e-2 -xmin -1.5 -xmax 1.5 -ymin -1.5 -ymax 1.5
tol = 1e-3
N = 60
Now running mpiexec -np 1 ../../maddm -N 60 -problem ex1 -sub_snes_rtol 1e-3 -sub_ksp_rtol 1e-3 -xmin -1.5 -xmax 1.5 -ymin -1.5 -ymax 1.5
N = 300
Now running mpiexec -np 1 ../../maddm -N 300 -problem ex1 -sub_snes_rtol 1e-3 -sub_ksp_rtol 1e-3 -xmin -1.5 -xmax 1.5 -ymin -1.5 -ymax 1.5
N = 600
Now running mpiexec -np 1 ../../maddm -N 600 -problem ex1 -sub_snes_rtol 1e-3 -sub_ksp_rtol 1e-3 -xmin -1.5 -xmax 1.5 -ymin -1.5 -ymax 1.5
tol = 1e-4
N = 60
Now running mpiexec -np 1 ../../maddm -N 60 -problem ex1 -sub_snes_rtol 1e-4 -sub_ksp_rtol 1e-4 -xmin -1.5 -xmax 1.5 -ymin -1.5 -ymax 1.5
N = 300
Now running mpiexec -np 1 ../../maddm -N 300 -problem ex1 -sub_snes_rtol 1e-4 -sub_ksp_rtol 1e-4 -xmin -1.5 -xmax 1.5 -ymin -1.5 -ymax 1.5
N = 600
Now running mpiexec -np 1 ../../maddm -N 600 -problem ex1 -sub_snes_rtol 1e-4 -sub_ksp_rtol 1e-4 -xmin -1.5 -xmax 1.5 -ymin -1.5 -ymax 1.5
tol = 1e-5
N = 60
Now running mpiexec -np 1 ../../maddm -N 60 -problem ex1 -sub_snes_rtol 1e-5 -sub_ksp_rtol 1e-5 -xmin -1.5 -xmax 1.5 -ymin -1.5 -ymax 1.5
N = 300
Now running mpiexec -np 1 ../../maddm -N 300 -problem ex1 -sub_snes_rtol 1e-5 -sub_ksp_rtol 1e-5 -xmin -1.5 -xmax 1.5 -ymin -1.5 -ymax 1.5
N = 600
Now running mpiexec -np 1 ../../maddm -N 600 -problem ex1 -sub_snes_rtol 1e-5 -sub_ksp_rtol 1e-5 -xmin -1.5 -xmax 1.5 -ymin -1.5 -ymax 1.5
tol = 1e-6
N = 60
Now running mpiexec -np 1 ../../maddm -N 60 -problem ex1 -sub_snes_rtol 1e-6 -sub_ksp_rtol 1e-6 -xmin -1.5 -xmax 1.5 -ymin -1.5 -ymax 1.5
N = 300
Now running mpiexec -np 1 ../../maddm -N 300 -problem ex1 -sub_snes_rtol 1e-6 -sub_ksp_rtol 1e-6 -xmin -1.5 -xmax 1.5 -ymin -1.5 -ymax 1.5
N = 600
Now running mpiexec -np 1 ../../maddm -N 600 -problem ex1 -sub_snes_rtol 1e-6 -sub_ksp_rtol 1e-6 -xmin -1.5 -xmax 1.5 -ymin -1.5 -ymax 1.5
[-2.0, 2.0]^2
tol = 1e-1
N = 80
Now running mpiexec -np 1 ../../maddm -N 80 -problem ex1 -sub_snes_rtol 1e-1 -sub_ksp_rtol 1e-1 -xmin -2.0 -xmax 2.0 -ymin -2.0 -ymax 2.0
N = 400
Now running mpiexec -np 1 ../../maddm -N 400 -problem ex1 -sub_snes_rtol 1e-1 -sub_ksp_rtol 1e-1 -xmin -2.0 -xmax 2.0 -ymin -2.0 -ymax 2.0
N = 800
Now running mpiexec -np 1 ../../maddm -N 800 -problem ex1 -sub_snes_rtol 1e-1 -sub_ksp_rtol 1e-1 -xmin -2.0 -xmax 2.0 -ymin -2.0 -ymax 2.0
tol = 1e-2
N = 80
Now running mpiexec -np 1 ../../maddm -N 80 -problem ex1 -sub_snes_rtol 1e-2 -sub_ksp_rtol 1e-2 -xmin -2.0 -xmax 2.0 -ymin -2.0 -ymax 2.0
N = 400
Now running mpiexec -np 1 ../../maddm -N 400 -problem ex1 -sub_snes_rtol 1e-2 -sub_ksp_rtol 1e-2 -xmin -2.0 -xmax 2.0 -ymin -2.0 -ymax 2.0
N = 800
Now running mpiexec -np 1 ../../maddm -N 800 -problem ex1 -sub_snes_rtol 1e-2 -sub_ksp_rtol 1e-2 -xmin -2.0 -xmax 2.0 -ymin -2.0 -ymax 2.0
tol = 1e-3
N = 80
Now running mpiexec -np 1 ../../maddm -N 80 -problem ex1 -sub_snes_rtol 1e-3 -sub_ksp_rtol 1e-3 -xmin -2.0 -xmax 2.0 -ymin -2.0 -ymax 2.0
N = 400
Now running mpiexec -np 1 ../../maddm -N 400 -problem ex1 -sub_snes_rtol 1e-3 -sub_ksp_rtol 1e-3 -xmin -2.0 -xmax 2.0 -ymin -2.0 -ymax 2.0
N = 800
Now running mpiexec -np 1 ../../maddm -N 800 -problem ex1 -sub_snes_rtol 1e-3 -sub_ksp_rtol 1e-3 -xmin -2.0 -xmax 2.0 -ymin -2.0 -ymax 2.0
tol = 1e-4
N = 80
Now running mpiexec -np 1 ../../maddm -N 80 -problem ex1 -sub_snes_rtol 1e-4 -sub_ksp_rtol 1e-4 -xmin -2.0 -xmax 2.0 -ymin -2.0 -ymax 2.0
N = 400
Now running mpiexec -np 1 ../../maddm -N 400 -problem ex1 -sub_snes_rtol 1e-4 -sub_ksp_rtol 1e-4 -xmin -2.0 -xmax 2.0 -ymin -2.0 -ymax 2.0
N = 800
Now running mpiexec -np 1 ../../maddm -N 800 -problem ex1 -sub_snes_rtol 1e-4 -sub_ksp_rtol 1e-4 -xmin -2.0 -xmax 2.0 -ymin -2.0 -ymax 2.0
tol = 1e-5
N = 80
Now running mpiexec -np 1 ../../maddm -N 80 -problem ex1 -sub_snes_rtol 1e-5 -sub_ksp_rtol 1e-5 -xmin -2.0 -xmax 2.0 -ymin -2.0 -ymax 2.0
N = 400
Now running mpiexec -np 1 ../../maddm -N 400 -problem ex1 -sub_snes_rtol 1e-5 -sub_ksp_rtol 1e-5 -xmin -2.0 -xmax 2.0 -ymin -2.0 -ymax 2.0
N = 800
Now running mpiexec -np 1 ../../maddm -N 800 -problem ex1 -sub_snes_rtol 1e-5 -sub_ksp_rtol 1e-5 -xmin -2.0 -xmax 2.0 -ymin -2.0 -ymax 2.0
tol = 1e-6
N = 80
Now running mpiexec -np 1 ../../maddm -N 80 -problem ex1 -sub_snes_rtol 1e-6 -sub_ksp_rtol 1e-6 -xmin -2.0 -xmax 2.0 -ymin -2.0 -ymax 2.0
N = 400
Now running mpiexec -np 1 ../../maddm -N 400 -problem ex1 -sub_snes_rtol 1e-6 -sub_ksp_rtol 1e-6 -xmin -2.0 -xmax 2.0 -ymin -2.0 -ymax 2.0
N = 800
Now running mpiexec -np 1 ../../maddm -N 800 -problem ex1 -sub_snes_rtol 1e-6 -sub_ksp_rtol 1e-6 -xmin -2.0 -xmax 2.0 -ymin -2.0 -ymax 2.0
slurmstepd: error: *** JOB 110523 ON node012 CANCELLED AT 2022-10-13T22:36:25 DUE TO TIME LIMIT ***
