#!/bin/bash -l
# This is a redo of the size test in Set1 with single-iteration newton.

## NAMING
#SBATCH -J j2
#SBATCH -p public
#SBATCH -o slurmout2


## partition/queue
#SBATCH -p dms-cpu

## EMAIL NOTIFICATION
#SBATCH --mail-user tt73@njit.edu
#SBATCH --mail-type=ALL
#SBATCH -A tt73

## RUNTIME  HOURS:MIN:SEC and MEMORY
#SBATCH -t 8:0:0
#SBATCH --mem=16G
#SBATCH -N 4

module load gnu8 mpich petsc

np=4
for N in {100,200,300,400}
do
   printf "N = $N\n" >> out2
   mpiexec -np $np ../../maddm -N $N -problem ex1 -sin >> out2
   mpiexec -np $np ../../maddm -N $N -problem ex2 -sin >> out2
   mpiexec -np $np ../../maddm -N $N -problem ex3 -sin >> out2
done