#!/bin/bash -l
# This is a redo of the size test in Set1 with single-iteration newton.

## NAMING
#SBATCH -J j2
#SBATCH -o slurmout2

## partition/queue
#SBATCH -p dms-cpu

## EMAIL NOTIFICATION
#SBATCH --mail-user tt73@njit.edu
#SBATCH --mail-type=ALL
#SBATCH -A tt73

## RUNTIME  HOURS:MIN:SEC and MEMORY
#SBATCH -t 8:0:0
#SBATCH --mem=0

## Task allocation
#SBATCH --ntasks 4
#SBATCH --nodes 4
#SBATCH --ntasks-per-node 1

module load gnu8 mpich petsc/3.12.0

rm -f out2a out2

np=4
for N in {100,200,300,400}
do
   printf "N = $N\n" >> out2a
   mpiexec -np $np ../../maddm -N $N -problem ex1 -sin >> out2a
   mpiexec -np $np ../../maddm -N $N -problem ex2 -sin >> out2a
   mpiexec -np $np ../../maddm -N $N -problem ex3 -sin >> out2a
   mpiexec -np $np ../../maddm -N $N -problem ex4 -sin >> out2a

   printf "N = $N\n" >> out2b
   mpiexec -np $np ../../maddm -N $N -problem ex1 -htn >> out2b
   mpiexec -np $np ../../maddm -N $N -problem ex2 -htn >> out2b
   mpiexec -np $np ../../maddm -N $N -problem ex3 -htn >> out2b
   mpiexec -np $np ../../maddm -N $N -problem ex4 -htn >> out2b
done