#!/bin/bash -l
# This is a redo of the overlap test in Set1 with high-tolerance newton.


## NAMING
#SBATCH -J j3
#SBATCH -p public
#SBATCH -o slurmout3

## partition/queue
#SBATCH -p dms-cpu

## EMAIL NOTIFICATION
#SBATCH --mail-user tt73@njit.edu
#SBATCH --mail-type=END
#SBATCH -A tt73

## RUNTIME  HOURS:MIN:SEC and MEMORY
#SBATCH -t 8:0:0
#SBATCH --mem=16G
#SBATCH -N 4

module load gnu8 mpich petsc

N=200
np=4
for op in {0.0,0.05,0.10,0.15,0.20}
do
   printf "overlap = $op\n" >> out3
   mpiexec -np $np ../../maddm -N $N -op $op -problem ex1 -htn >> out3
   mpiexec -np $np ../../maddm -N $N -op $op -problem ex2 -htn >> out3
   mpiexec -np $np ../../maddm -N $N -op $op -problem ex3 -htn >> out3
done