#!/bin/bash -l
# This is a redo of the size test in Set1 with high-tolerance newton.

## NAMING
#SBATCH -J j4
#SBATCH -p public
#SBATCH -o slurmout4

## partition/queue
#SBATCH -p dms-cpu

## EMAIL NOTIFICATION
#SBATCH --mail-user tt73@njit.edu
#SBATCH --mail-type=END
#SBATCH -A tt73

## RUNTIME  HOURS:MIN:SEC and MEMORY
#SBATCH -t 3:0:0
#SBATCH --mem=16G
#SBATCH -N 4

module load gnu8 mpich petsc

np=4
for N in {100,200,300,400}
do
   printf "N = $N\n" >> out4
   mpiexec -np $np ../../maddm -N $N -problem ex1 -htn >> out4
   mpiexec -np $np ../../maddm -N $N -problem ex2 -htn >> out4
   mpiexec -np $np ../../maddm -N $N -problem ex3 -htn >> out4
done