#!/bin/bash -l
#SBATCH -J j6
#SBATCH -o slurmout6
#SBATCH -p dms-cpu
#SBATCH --mail-user tt73@njit.edu
#SBATCH -A tt73
#SBATCH -t 8:0:0
#SBATCH --nodes 6
#SBATCH --ntasks 6
#SBATCH --ntasks-per-node 1
#SBATCH --exclusive
module load gnu8 mpich petsc/3.12.0
N=300
mpirun ../../maddm -N $N -problem ex1 -snes_type newtonls -snes_linesearch_order 2 -ksp_type pipefgmres -pc_type bjacobi -ksp_rtol 1e-5 >> out6
mpirun ../../maddm -N $N -problem ex2 -snes_type newtonls -snes_linesearch_order 2 -ksp_type pipefgmres -pc_type bjacobi -ksp_rtol 1e-5 >> out6
mpirun ../../maddm -N $N -problem ex3 -snes_type newtonls -snes_linesearch_order 2 -ksp_type pipefgmres -pc_type bjacobi -ksp_rtol 1e-5 >> out6
mpirun ../../maddm -N $N -problem ex4 -snes_type newtonls -snes_linesearch_order 2 -ksp_type pipefgmres -pc_type bjacobi -ksp_rtol 1e-5 >> out6
