#!/bin/bash -l
#SBATCH -J j9
#SBATCH -o slurmout9
#SBATCH -p dms-cpu
#SBATCH --mail-user tt73@njit.edu
#SBATCH -A tt73
#SBATCH -t 8:0:0
#SBATCH --mem=16G
#SBATCH --nodes 9
#SBATCH --ntasks 9
module load gnu8 mpich petsc/3.12.0
N=300
mpirun ../../maddm -N $N -problem ex1 -snes_type newtonls -snes_linesearch_order 2 -ksp_type pipefgmres -pc_type bjacobi >> out9
mpirun ../../maddm -N $N -problem ex2 -snes_type newtonls -snes_linesearch_order 2 -ksp_type pipefgmres -pc_type bjacobi >> out9
mpirun ../../maddm -N $N -problem ex3 -snes_type newtonls -snes_linesearch_order 2 -ksp_type pipefgmres -pc_type bjacobi >> out9
mpirun ../../maddm -N $N -problem ex4 -snes_type newtonls -snes_linesearch_order 2 -ksp_type pipefgmres -pc_type bjacobi >> out9
