#!/bin/bash -l
#SBATCH -J j6
#SBATCH -o slurmout6
#SBATCH -p dms-cpu
#SBATCH -A tt73
#SBATCH -t 8:0:0
#SBATCH --mem=0G
#SBATCH --nodes 6
#SBATCH --ntasks 6
#SBATCH --ntasks-per-node 1
module load gnu8 mpich petsc/3.12.0
mpirun ../../maddm -Nx 300 -Ny 450 -op 0.000000 -problem ex1 -snes_type newtonls -snes_linesearch_order 2 -ksp_type pipefgmres >> out6
mpirun ../../maddm -Nx 300 -Ny 450 -op 0.000000 -problem ex2 -snes_type newtonls -snes_linesearch_order 2 -ksp_type pipefgmres >> out6
mpirun ../../maddm -Nx 300 -Ny 450 -op 0.000000 -problem ex3 -snes_type newtonls -snes_linesearch_order 2 -ksp_type pipefgmres >> out6
mpirun ../../maddm -Nx 300 -Ny 450 -op 0.000000 -problem ex4 -snes_type newtonls -snes_linesearch_order 2 -ksp_type pipefgmres >> out6
