#!/bin/bash -l
#SBATCH -J j9
#SBATCH -p public
#SBATCH -o slurmout9
#SBATCH -p dms-cpu
#SBATCH --mail-user tt73@njit.edu
#SBATCH -A tt73
#SBATCH -t 8:0:0
#SBATCH --mem=16G
#SBATCH --nodes 9
#SBATCH --ntasks 9
module load gnu8 mpich petsc
mpirun ../../maddm -Nx 409 -Ny 409 -op 0.100000 -problem ex1 -snes_type newtonls -ksp_rtol 1e-2 -snes_linesearch_order 2 -ksp_type pipefgmres >> out9
mpirun ../../maddm -Nx 409 -Ny 409 -op 0.100000 -problem ex2 -snes_type newtonls -ksp_rtol 1e-2 -snes_linesearch_order 2 -ksp_type pipefgmres >> out9
mpirun ../../maddm -Nx 409 -Ny 409 -op 0.100000 -problem ex3 -snes_type newtonls -ksp_rtol 1e-2 -snes_linesearch_order 2 -ksp_type pipefgmres >> out9
mpirun ../../maddm -Nx 409 -Ny 409 -op 0.100000 -problem ex4 -snes_type newtonls -ksp_rtol 1e-2 -snes_linesearch_order 2 -ksp_type pipefgmres >> out9
