#!/bin/bash -l
#SBATCH -J j2-low2
#SBATCH -o slurmout2
#SBATCH -p lowpriority
#SBATCH --constraint=avx512
#SBATCH -A tt73
#SBATCH -t 3:0:0
#SBATCH --mem=0G
#SBATCH --nodes 2
#SBATCH --ntasks 2
#SBATCH --ntasks-per-node 1
module load gnu8 mpich petsc/3.12.0
N=300
mpirun ../../maddm -N $N -problem ex1 -sin -op 0.05 >> out2
mpirun ../../maddm -N $N -problem ex2 -sin -op 0.05 >> out2
mpirun ../../maddm -N $N -problem ex3 -sin -op 0.05 >> out2
mpirun ../../maddm -N $N -problem ex4 -sin -op 0.05 >> out2
