#!/bin/bash -l
# This is a job submission file on the njit cluster Stheno.
# Submit this by typing `sbatch shjob`

## NAMING
#SBATCH -J j5
#SBATCH -p public
#SBATCH -o test.output
#SBATCH -e test.output

## partition/queue
#SBATCH -p dms-cpu

## EMAIL NOTIFICATION
#SBATCH --mail-user tt73@njit.edu
#SBATCH --mail-type=ALL
#SBATCH -A tt73

## RUNTIME  HOURS:MIN:SEC and MEMORY
#SBATCH -t 16:0:0
#SBATCH --mem=32G
#SBATCH -N 9

module load gnu8
module load mpich
module load petsc

bash test5.sh > out_test5