#!/bin/bash -l
# This is a job submission file on the njit cluster Stheno.
# Submit this by typing `sbatch job`

## NAMING
#SBATCH -J set3
#SBATCH -p public
#SBATCH -o test.output
#SBATCH -e test.output

## partition/queue
#SBATCH -p dms-cpu

## EMAIL NOTIFICATION
#SBATCH --mail-user tt73@njit.edu
#SBATCH --mail-type=ALL
#SBATCH -A tt73

## RUNTIME  HOURS:MIN:SEC and MEMORY
#SBATCH -t 8:0:0
#SBATCH --mem=16G
#SBATCH -N 4

module load gnu8 mpich petsc

bash test4b.sh > out4b