#!/bin/bash -l
#SBATCH -J j1
#SBATCH -o slurmout1
#SBATCH -p dms-cpu
#SBATCH -A tt73
#SBATCH -t 8:0:0
#SBATCH --nodes 1
#SBATCH --ntasks 2
#SBATCH --ntasks-per-node 2
module load gnu8 mpich petsc/3.12.0
mpirun ../../maddm -Nx 150 -Ny 272 -op 0.100000 -problem ex1 -sin >> out1
mpirun ../../maddm -Nx 150 -Ny 272 -op 0.100000 -problem ex2 -sin >> out1
mpirun ../../maddm -Nx 150 -Ny 272 -op 0.100000 -problem ex3 -sin >> out1
mpirun ../../maddm -Nx 150 -Ny 272 -op 0.100000 -problem ex4 -sin >> out1
