#!/bin/bash -l
#SBATCH -J j1
#SBATCH -p public
#SBATCH -o slurmout1
#SBATCH -p dms-cpu
#SBATCH --mail-user tt73@njit.edu
#SBATCH -A tt73
#SBATCH -t 8:0:0
#SBATCH --mem=16G
#SBATCH --nodes 1
#SBATCH --ntasks 1
module load gnu8 mpich petsc
mpirun ../../maddm -Nx 100 -Ny 100 -problem ex1 -sin >> out1
mpirun ../../maddm -Nx 100 -Ny 100 -problem ex2 -sin >> out1
mpirun ../../maddm -Nx 100 -Ny 100 -problem ex3 -sin >> out1
mpirun ../../maddm -Nx 100 -Ny 100 -problem ex4 -sin >> out1
