#!/bin/bash -l
#SBATCH -J j16
#SBATCH -p public
#SBATCH -o slurmout16
#SBATCH --mail-user tt73@njit.edu
#SBATCH -A tt73
#SBATCH -t 8:0:0
#SBATCH --mem=16G
#SBATCH --nodes 16
#SBATCH --ntasks 16
module load gnu8 mpich petsc
mpirun ../../maddm -Nx 363 -Ny 363 -op 0.100000 -problem ex1 -sin >> out16
mpirun ../../maddm -Nx 363 -Ny 363 -op 0.100000 -problem ex2 -sin >> out16
mpirun ../../maddm -Nx 363 -Ny 363 -op 0.100000 -problem ex3 -sin >> out16
mpirun ../../maddm -Nx 363 -Ny 363 -op 0.100000 -problem ex4 -sin >> out16
