#!/bin/bash -l
#SBATCH -J j3
#SBATCH -o slurmout3
#SBATCH -p dms-cpu
#SBATCH -A tt73
#SBATCH -t 8:0:0
#SBATCH --nodes 3
#SBATCH --ntasks 6
#SBATCH --ntasks-per-node 2
module load gnu8 mpich petsc/3.12.0
mpirun ../../maddm -Nx 272 -Ny 409 -op 0.100000 -problem ex1 -sin >> out3
mpirun ../../maddm -Nx 272 -Ny 409 -op 0.100000 -problem ex2 -sin >> out3
mpirun ../../maddm -Nx 272 -Ny 409 -op 0.100000 -problem ex3 -sin >> out3
mpirun ../../maddm -Nx 272 -Ny 409 -op 0.100000 -problem ex4 -sin >> out3
