#!/bin/bash -l
#SBATCH -J j4
#SBATCH -p public
#SBATCH -o slurmout4
#SBATCH -p dms-cpu
#SBATCH --mail-user tt73@njit.edu
#SBATCH -A tt73
#SBATCH -t 8:0:0
#SBATCH --mem=16G
#SBATCH --nodes 4
#SBATCH --ntasks 4
module load gnu8 mpich petsc
mpirun ../../maddm -Nx 200 -Ny 200 -problem ex1 -sin >> out4
mpirun ../../maddm -Nx 200 -Ny 200 -problem ex2 -sin >> out4
mpirun ../../maddm -Nx 200 -Ny 200 -problem ex3 -sin >> out4
mpirun ../../maddm -Nx 200 -Ny 200 -problem ex4 -sin >> out4
