#!/bin/bash -l
## This is the overlap percentage test.
## Bumping up the mesh size to 300x300


## NAMING
#SBATCH -J j3
#SBATCH -p public
#SBATCH -o slurmout1
#SBATCH -e slurmout1

## partition/queue
#SBATCH -p dms-cpu

## EMAIL NOTIFICATION
#SBATCH --mail-user tt73@njit.edu
##SBATCH --mail-type=END ## don't need this
#SBATCH -A tt73

## RUNTIME HOURS:MIN:SEC and MEMORY
#SBATCH -t 8:0:0
#SBATCH --mem=16G
#SBATCH -N 4
#SBATCH --ntasks-per-node 1
#SBATCH --exclusive

module load gnu8 mpich petsc/3.12.0

rm -f out3

N=300
np=4
for op in {0.0,0.05,0.10,0.15,0.20,0.25,0.30,0.35,.40}
do
   printf "overlap = $op\n" >> out3
   mpiexec -np $np ../../maddm -N $N -op $op -sin -problem ex1 >> out3
   mpiexec -np $np ../../maddm -N $N -op $op -sin -problem ex2 >> out3
   mpiexec -np $np ../../maddm -N $N -op $op -sin -problem ex3 >> out3
   mpiexec -np $np ../../maddm -N $N -op $op -sin -problem ex4 >> out3
done