#!/bin/bash -l
#SBATCH -J j6
#SBATCH -o slurmout6
#SBATCH -p dms-cpu
#SBATCH -A tt73
#SBATCH -t 8:0:0
#SBATCH --mem=0G
#SBATCH --nodes 6
#SBATCH --ntasks 6
#SBATCH --ntasks-per-node 1
module load gnu8 mpich petsc/3.12.0
mpirun ../../maddm -Nx 230 -Ny 346 -op 0.300000 -problem ex1 -aspin >> out6
mpirun ../../maddm -Nx 230 -Ny 346 -op 0.300000 -problem ex2 -aspin >> out6
mpirun ../../maddm -Nx 230 -Ny 346 -op 0.300000 -problem ex3 -aspin >> out6
mpirun ../../maddm -Nx 230 -Ny 346 -op 0.300000 -problem ex4 -aspin >> out6
