#!/bin/bash -l
#SBATCH -J j8
#SBATCH -p public
#SBATCH -o out8
#SBATCH -p dms-cpu
#SBATCH --mail-user tt73@njit.edu
#SBATCH -A tt73
#SBATCH -t 8:0:0
#SBATCH --mem=16G
#SBATCH --nodes 8
#SBATCH --ntasks 8
#SBATCH --exclusive
module load gnu8
module load mpich
module load petsc
N=300
mpirun ../../maddm -N $N -problem ex1 -snes_max_it 500
mpirun ../../maddm -N $N -problem ex2 -snes_max_it 500
mpirun ../../maddm -N $N -problem ex3 -snes_max_it 500
