#!/bin/bash -l
#SBATCH -J j8
#SBATCH -o slurmout8
#SBATCH -p dms-cpu
#SBATCH --mail-user tt73@njit.edu
#SBATCH -A tt73
#SBATCH -t 8:0:0
#SBATCH --mem=0G
#SBATCH --nodes 8
#SBATCH --ntasks 8
#SBATCH --ntasks-per-node 1
module load gnu8 mpich petsc/3.12.0
N=300
mpirun ../../maddm -N $N -problem ex1 -htn >> out8
mpirun ../../maddm -N $N -problem ex2 -htn >> out8
mpirun ../../maddm -N $N -problem ex3 -htn >> out8
mpirun ../../maddm -N $N -problem ex4 -htn >> out8
