#!/bin/bash -l
#SBATCH -J j9
#SBATCH -p public
#SBATCH -o slurmout9
#SBATCH -p dms-cpu
#SBATCH --mail-user tt73@njit.edu
#SBATCH -A tt73
#SBATCH -t 8:0:0
#SBATCH --mem=16G
#SBATCH --nodes 9
#SBATCH --ntasks 9
module load gnu8 mpich petsc
N=300
mpirun ../../maddm -N $N -problem ex1 -sub_snes_linesearch_type l2 -sub_snes_max_it 1 -sub_ksp_rtol 1e-1 -snes_max_it 900 >> out9
mpirun ../../maddm -N $N -problem ex2 -sub_snes_linesearch_type l2 -sub_snes_max_it 1 -sub_ksp_rtol 1e-1 -snes_max_it 900 >> out9
mpirun ../../maddm -N $N -problem ex3 -sub_snes_linesearch_type l2 -sub_snes_max_it 1 -sub_ksp_rtol 1e-1 -snes_max_it 900 >> out9
mpirun ../../maddm -N $N -problem ex4 -sub_snes_linesearch_type l2 -sub_snes_max_it 1 -sub_ksp_rtol 1e-1 -snes_max_it 900 >> out9
