Starting /home/t/tt73/.bash_profile ... standard AFS bash profile

========================
Home directory : /home/t/tt73 is not in AFS -- skipping quota check
========================

On host node009 :
	 10:16:11 up 82 days, 17:24,  0 users,  load average: 0.00, 0.01, 0.05

=== === === Your Kerberos ticket and AFS token status === === ===
klist: No credentials cache found (filename: /tmp/krb5cc_90502_AdNwhSeijg)
Kerberos : 
AFS      : 

Loading default modules ...
Create file : "/home/t/tt73/.modules" to customize.


Currently Loaded Modules:
  1) gnu8/8.3.0    3) phdf5/1.10.5     5) scalapack/2.0.2
  2) mpich/3.3.1   4) openblas/0.3.7   6) petsc/3.12.0

 

