Starting /home/t/tt73/.bash_profile ... standard AFS bash profile

========================
Home directory : /home/t/tt73 is not in AFS -- skipping quota check
========================

On host node000 :
	 16:49:32 up 748 days, 22:02,  0 users,  load average: 2.37, 3.17, 1.93

=== === === Your Kerberos ticket and AFS token status === === ===
klist: No credentials cache found (filename: /tmp/krb5cc_90502_wLCBymYwNw)
Kerberos : 
AFS      : 

Loading default modules ...
Create file : "/home/t/tt73/.modules" to customize.

No modules loaded
