#!/bin/bash -l
#SBATCH -J j2
#SBATCH -o slurmout2
#SBATCH -p dms-cpu
#SBATCH -A tt73
#SBATCH -t 8:0:0
#SBATCH --mem=0G
#SBATCH --nodes 2
#SBATCH --ntasks 2
#SBATCH --ntasks-per-node 1
module load gnu8 mpich petsc/3.12.0
mpirun ../../maddm -Nx 150 -Ny 230 -op 0.300000 -problem ex1 -htn >> out2
mpirun ../../maddm -Nx 150 -Ny 230 -op 0.300000 -problem ex2 -htn >> out2
mpirun ../../maddm -Nx 150 -Ny 230 -op 0.300000 -problem ex3 -htn >> out2
mpirun ../../maddm -Nx 150 -Ny 230 -op 0.300000 -problem ex4 -htn >> out2
