#!/bin/bash -l
#SBATCH -J j8
#SBATCH -o slurmout8
#SBATCH -p dms-cpu
#SBATCH -A tt73
#SBATCH -t 8:0:0
#SBATCH --mem=0G
#SBATCH --nodes 8
#SBATCH --ntasks 8
#SBATCH --ntasks-per-node 1
module load gnu8 mpich petsc/3.12.0
mpirun ../../maddm -Nx 307 -Ny 615 -op 0.300000 -problem ex1 -htn >> out8
mpirun ../../maddm -Nx 307 -Ny 615 -op 0.300000 -problem ex2 -htn >> out8
mpirun ../../maddm -Nx 307 -Ny 615 -op 0.300000 -problem ex3 -htn >> out8
mpirun ../../maddm -Nx 307 -Ny 615 -op 0.300000 -problem ex4 -htn >> out8
