#!/bin/bash -l
#SBATCH -J j9
#SBATCH -p public
#SBATCH -o slurmout9
#SBATCH -p dms-cpu
#SBATCH --mail-user tt73@njit.edu
#SBATCH -A tt73
#SBATCH -t 8:0:0
#SBATCH --mem=16G
#SBATCH --nodes 9
#SBATCH --ntasks 9
module load gnu8 mpich petsc
mpirun ../../maddm -Nx 250 -Ny 250 -op 0.200000 -problem ex1 -htn >> out9
mpirun ../../maddm -Nx 250 -Ny 250 -op 0.200000 -problem ex2 -htn >> out9
mpirun ../../maddm -Nx 250 -Ny 250 -op 0.200000 -problem ex3 -htn >> out9
mpirun ../../maddm -Nx 250 -Ny 250 -op 0.200000 -problem ex4 -htn >> out9
