Starting /home/t/tt73/.bash_profile ... standard AFS bash profile

========================
Home directory : /home/t/tt73 is not in AFS -- skipping quota check
========================

On host node009 :
	 12:38:46 up 46 days, 19:46,  0 users,  load average: 0.00, 0.03, 0.05

=== === === Your Kerberos ticket and AFS token status === === ===
klist: No credentials cache found (filename: /tmp/krb5cc_90502_skhjyUPJMT)
Kerberos : 
AFS      : 

Loading default modules ...
Create file : "/home/t/tt73/.modules" to customize.


Currently Loaded Modules:
  1) gnu8/8.3.0    3) phdf5/1.10.5     5) scalapack/2.0.2
  2) mpich/3.3.1   4) openblas/0.3.7   6) petsc/3.12.0

 

[-0.5, 0.5]^2
[-1.0, 1.0]^2
[-1.5, 1.5]^2
[-2.0, 2.0]^2
