Starting /home/t/tt73/.bash_profile ... standard AFS bash profile

========================
Home directory : /home/t/tt73 is not in AFS -- skipping quota check
========================

On host node009 :
	 11:04:26 up 83 days, 18:12,  0 users,  load average: 0.00, 0.13, 0.34

=== === === Your Kerberos ticket and AFS token status === === ===
klist: No credentials cache found (filename: /tmp/krb5cc_90502_agF7fn9AsD)
Kerberos : 
AFS      : 

Loading default modules ...
Create file : "/home/t/tt73/.modules" to customize.


Currently Loaded Modules:
  1) python/3.8   3) mpich/3.3.1    5) openblas/0.3.7    7) petsc/3.12.0
  2) gnu8/8.3.0   4) phdf5/1.10.5   6) scalapack/2.0.2

 

[-0.5, 0.5]^2
[-1.0, 1.0]^2
[-1.5, 1.5]^2
[-2.0, 2.0]^2
