Starting /home/t/tt73/.bash_profile ... standard AFS bash profile

========================
Home directory : /home/t/tt73 is not in AFS -- skipping quota check
========================

On host node000 :
	 10:34:44 up 691 days, 16:47,  0 users,  load average: 0.08, 0.03, 0.05

=== === === Your Kerberos ticket and AFS token status === === ===
klist: No credentials cache found (filename: /tmp/krb5cc_90502_skhjyUPJMT)
Kerberos : 
AFS      : 

Loading default modules ...
Create file : "/home/t/tt73/.modules" to customize.

No modules loaded
[-0.5, 0.5]^2
[-1.0, 1.0]^2
[-1.5, 1.5]^2
[-2.0, 2.0]^2
