#!/bin/bash -l
#SBATCH -J j1
#SBATCH -p public
#SBATCH -o out1
#SBATCH -p dms-cpu
#SBATCH --mail-user tt73@njit.edu
#SBATCH -A tt73
#SBATCH -t 8:0:0
#SBATCH --mem=16G
#SBATCH --nodes 1
#SBATCH --ntasks 1
module load gnu8 mpich petsc
N=300
mpirun ../../maddm -N $N -problem ex1 -aspin
mpirun ../../maddm -N $N -problem ex2 -aspin
mpirun ../../maddm -N $N -problem ex3 -aspin
