#!/bin/bash -l
#SBATCH -J j6
#SBATCH -p public
#SBATCH -o slurmout6
#SBATCH -p dms-cpu
#SBATCH --mail-user tt73@njit.edu
#SBATCH -A tt73
#SBATCH -t 8:0:0
#SBATCH --mem=16G
#SBATCH --nodes 6
#SBATCH --ntasks 6
module load gnu8 mpich petsc
N=300
mpirun ../../maddm -N $N -problem ex1 -sin >> out6
mpirun ../../maddm -N $N -problem ex2 -sin >> out6
mpirun ../../maddm -N $N -problem ex3 -sin >> out6
