#!/bin/bash -l
## This is a serial test for the default Newton method in PETSc.
## It uses the regular GMRES with ILU PC.

## Set the name of job
#SBATCH -J serial2
#SBATCH -p public

## Set partition/queue
#SBATCH -p dms-cpu


## RUNTIME  HOURS:MIN:SEC and MEMORY
#SBATCH -t 8:0:0
#SBATCH --mem=16G
#SBATCH -N 1

## Modules needed for PETSc
module load gnu8 mpich petsc

# for N in 100 150 200 250 300 350 400 450 500
for N in 10000       22500       40000       62500       90000      122500      160000      202500      250000
do
   printf "N = $N:\n" >> out2
   ../../maddm -N $N -problem ex1 -snes_type newtonls -dim 1 >> out2
   ../../maddm -N $N -problem ex2 -snes_type newtonls -dim 1 >> out2
   ../../maddm -N $N -problem ex3 -snes_type newtonls -dim 1 >> out2
   ../../maddm -N $N -problem ex4 -snes_type newtonls -dim 1 >> out2
done
