Starting /home/t/tt73/.bash_profile ... standard AFS bash profile

========================
Home directory : /home/t/tt73 is not in AFS -- skipping quota check
========================

On host node000 :
	 14:29:24 up 692 days, 20:42,  0 users,  load average: 0.10, 0.26, 0.31

=== === === Your Kerberos ticket and AFS token status === === ===
klist: No credentials cache found (filename: /tmp/krb5cc_90502_skhjyUPJMT)
Kerberos : 
AFS      : 

Loading default modules ...
Create file : "/home/t/tt73/.modules" to customize.


Currently Loaded Modules:
  1) python/3.8   3) openblas/0.3.7   5) phdf5/1.10.5      7) petsc/3.12.0
  2) gnu8/8.3.0   4) mpich/3.3.1      6) scalapack/2.0.2

 

