#!/bin/bash -l
#SBATCH -J j1
#SBATCH -o slurmout1
#SBATCH -p dms-cpu
#SBATCH -A tt73
#SBATCH -t 8:0:0
#SBATCH --mem=0G
#SBATCH --nodes 1
#SBATCH --ntasks 1
#SBATCH --ntasks-per-node 1
module load gnu8 mpich petsc/3.12.0
mpirun ../../maddm -Nx 100 -Ny 100 -op 0.100000 -problem ex1 >> out1
mpirun ../../maddm -Nx 100 -Ny 100 -op 0.100000 -problem ex2 >> out1
mpirun ../../maddm -Nx 100 -Ny 100 -op 0.100000 -problem ex3 >> out1
mpirun ../../maddm -Nx 100 -Ny 100 -op 0.100000 -problem ex4 >> out1
