#!/bin/bash -l
#SBATCH -J j4
#SBATCH -o slurmout4
#SBATCH -p dms-cpu
#SBATCH -A tt73
#SBATCH -t 8:0:0
#SBATCH --mem=0G
#SBATCH --nodes 4
#SBATCH --ntasks 4
#SBATCH --ntasks-per-node 1
module load gnu8 mpich petsc/3.12.0
mpirun ../../maddm -Nx 272 -Ny 272 -op 0.100000 -problem ex1 -sin >> out4
mpirun ../../maddm -Nx 272 -Ny 272 -op 0.100000 -problem ex2 -sin >> out4
mpirun ../../maddm -Nx 272 -Ny 272 -op 0.100000 -problem ex3 -sin >> out4
mpirun ../../maddm -Nx 272 -Ny 272 -op 0.100000 -problem ex4 -sin >> out4
