#!/bin/bash -l
#SBATCH -J j6
#SBATCH -o slurmout6
#SBATCH -p dms-cpu
#SBATCH -A tt73
#SBATCH -t 8:0:0
#SBATCH --mem=0G
#SBATCH --nodes 6
#SBATCH --ntasks 6
#SBATCH --ntasks-per-node 1
module load gnu8 mpich petsc/3.12.0
mpirun ../../maddm -Nx 272 -Ny 409 -op 0.100000 -problem ex1 -sin >> out6
mpirun ../../maddm -Nx 272 -Ny 409 -op 0.100000 -problem ex2 -sin >> out6
mpirun ../../maddm -Nx 272 -Ny 409 -op 0.100000 -problem ex3 -sin >> out6
mpirun ../../maddm -Nx 272 -Ny 409 -op 0.100000 -problem ex4 -sin >> out6
