#!/bin/bash -l
#SBATCH -J j8
#SBATCH -o slurmout8
#SBATCH -p dms-cpu
#SBATCH -A tt73
#SBATCH -t 8:0:0
#SBATCH --mem=0G
#SBATCH --nodes 8
#SBATCH --ntasks 8
#SBATCH --ntasks-per-node 1
module load gnu8 mpich petsc/3.12.0
mpirun ../../maddm -Nx 181 -Ny 363 -op 0.100000 -problem ex1 -sin >> out8
mpirun ../../maddm -Nx 181 -Ny 363 -op 0.100000 -problem ex2 -sin >> out8
mpirun ../../maddm -Nx 181 -Ny 363 -op 0.100000 -problem ex3 -sin >> out8
mpirun ../../maddm -Nx 181 -Ny 363 -op 0.100000 -problem ex4 -sin >> out8
