#!/bin/bash -l
#SBATCH -J j6
#SBATCH -o slurmout6
#SBATCH -p dms-cpu
#SBATCH --mail-user tt73@njit.edu
#SBATCH -A tt73
#SBATCH -t 8:0:0
#SBATCH --nodes 6
#SBATCH --ntasks 6
#SBATCH --ntasks-per-node 1
#SBATCH --exclusive
module load gnu8 mpich petsc/3.12.0
N=300
mpirun ../../maddm -N $N -problem ex1 -aspin >> out6
mpirun ../../maddm -N $N -problem ex2 -aspin >> out6
mpirun ../../maddm -N $N -problem ex3 -aspin >> out6
mpirun ../../maddm -N $N -problem ex4 -aspin >> out6
