#!/bin/bash -l
#SBATCH -J j6
#SBATCH -p public
#SBATCH -o out6
#SBATCH -p dms-cpu
#SBATCH --mail-user tt73@njit.edu
#SBATCH -A tt73
#SBATCH -t 8:0:0
#SBATCH --mem=16G
#SBATCH --nodes 6
#SBATCH --ntasks 6
module load gnu8 mpich petsc
N=300
mpirun ../../maddm -N $N -problem ex1 -snes_type newtonls -ksp_rtol 1e-2 -snes_linesearch_order 2 -ksp_type pipefgmres
mpirun ../../maddm -N $N -problem ex2 -snes_type newtonls -ksp_rtol 1e-2 -snes_linesearch_order 2 -ksp_type pipefgmres
mpirun ../../maddm -N $N -problem ex3 -snes_type newtonls -ksp_rtol 1e-2 -snes_linesearch_order 2 -ksp_type pipefgmres
