#!/bin/bash -l
#SBATCH -J j1
#SBATCH -o slurmout1
#SBATCH -p dms-cpu
#SBATCH --mail-user tt73@njit.edu
#SBATCH -A tt73
#SBATCH -t 8:0:0
#SBATCH --mem=0
#SBATCH --ntasks 4
#SBATCH --nodes 4
#SBATCH --ntasks-per-node 1

module load gnu8 mpich petsc/3.12.0

rm -f out1a out1b

N=200
np=4
for op in {0.0,0.05,0.10,0.15,0.20,0.25}
do
   printf "overlap = $op\n" >> out1a
   mpirun ../../maddm -N $N -op $op -problem ex1 -sin >> out1a
   mpirun ../../maddm -N $N -op $op -problem ex2 -sin >> out1a
   mpirun ../../maddm -N $N -op $op -problem ex3 -sin >> out1a
   mpirun ../../maddm -N $N -op $op -problem ex4 -sin >> out1a

   printf "overlap = $op\n" >> out1b
   mpirun -np $np ../../maddm -N $N -op $op -problem ex1 -htn >> out1b
   mpirun -np $np ../../maddm -N $N -op $op -problem ex2 -htn >> out1b
   mpirun -np $np ../../maddm -N $N -op $op -problem ex3 -htn >> out1b
   mpirun -np $np ../../maddm -N $N -op $op -problem ex4 -htn >> out1b
done