#!/bin/bash -l
#SBATCH -J opt
#SBATCH -p public
#SBATCH -o slurmout9
#SBATCH -p dms-cpu
#SBATCH --mail-user tt73@njit.edu
#SBATCH -A tt73
#SBATCH -t 8:0:0
#SBATCH --mem=16G
#SBATCH --nodes 9
#SBATCH --ntasks 9
#SBATCH --ntasks-per-node 1
module load gnu8 mpich petsc/3.12.0
N=350
rm -f out9nks
for ktol in {1e-1,1e-2,1e-3,1e-4,1e-5}
do
   mpiexec -np 9 ../../maddm -N $N -problem ex5 -nks -op 0 -ksp_rtol $ktol >> out9nks
done