#!/bin/bash -l
#SBATCH -J opt
#SBATCH -p public
#SBATCH -o slurmout9
#SBATCH -p dms-cpu
#SBATCH --mail-user tt73@njit.edu
#SBATCH -A tt73
#SBATCH -t 8:0:0
#SBATCH --mem=16G
#SBATCH --nodes 9
#SBATCH --ntasks 9
#SBATCH --ntasks-per-node 1
module load gnu8 mpich petsc/3.12.0
N=200
rm -f out9sin
for op in {0.05,0.10,0.15,0.20,0.25,0.30,0.35}
do
   mpiexec -np 9 ../../maddm -N $N -problem ex5 -sin -op $op -sub_ksp_rtol 1e-1 >> out9sin
done
