#!/bin/bash -l
#SBATCH -J j9
#SBATCH -o slurmout9
#SBATCH -p dms-cpu
#SBATCH -A tt73
#SBATCH -t 8:0:0
#SBATCH --nodes 9
#SBATCH --ntasks 9
#SBATCH --ntasks-per-node 1
#SBATCH --exclusive
module load gnu8 mpich petsc/3.12.0
N=300
mpirun ../../maddm -N $N -problem ex1 -op 0.1 -snes_type ngmres -npc_snes_type newtonls >> out9
mpirun ../../maddm -N $N -problem ex2 -op 0.1 -snes_type ngmres -npc_snes_type newtonls >> out9
mpirun ../../maddm -N $N -problem ex3 -op 0.1 -snes_type ngmres -npc_snes_type newtonls >> out9
mpirun ../../maddm -N $N -problem ex4 -op 0.1 -snes_type ngmres -npc_snes_type newtonls >> out9
