#!/bin/bash -l
#SBATCH -J j16
#SBATCH -o slurmout16
#SBATCH -p lowpriority
#SBATCH --constraint=avx512
#SBATCH -A tt73
#SBATCH -t 8:0:0
#SBATCH --mem=0G
#SBATCH --nodes 16
#SBATCH --ntasks 16
#SBATCH --ntasks-per-node 1
module load gnu8 mpich petsc/3.12.0
N=300
op=0.10
mpirun ../../../maddm -N $N -problem ex1 -sin -op $op >> out16
mpirun ../../../maddm -N $N -problem ex2 -sin -op $op >> out16
mpirun ../../../maddm -N $N -problem ex3 -sin -op $op >> out16
mpirun ../../../maddm -N $N -problem ex4 -sin -op $op >> out16
